CREATE TABLE IF NOT EXISTS secrets (
	id SERIAL PRIMARY KEY,
	user_id SERIAL REFERENCES users(id),
	name VARCHAR(128) NOT NULL,
	secret VARCHAR(256) NOT NULL,
	encrypted BOOL NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
)
